const mongoose = require('mongoose')
const { Schema } = mongoose

const orderItemSchema = new Schema({
    productId: {
        type: Schema.Types.ObjectId,
        ref: 'Product',
        required: true
    },
    variantId: {
        type: Schema.Types.ObjectId,
        ref: 'ProductVariant',
        required: true
    },
    productName: {
        type: String,
        required: true
    },
    variantName: {
        type: String,
        required: true
    },
    quantity: {
        type: Number,
        required: true,
        min: 1
    },
    unitPrice: {
        type: Number,
        required: true,
        min: 0
    },
    totalPrice: {
        type: Number,
        required: true,
        min: 0
    },
    image: String
}, { _id: false })

const orderSchema = new Schema({
    orderNumber: {
        type: String,
        unique: true,
        required: false // Auto-generated by pre-save hook
        // Format: ORD-YYYYMMDD-XXXX (auto-generated)
    },
    userId: {
        type: Schema.Types.ObjectId,
        ref: 'users',
        required: [true, "User ID is required"]
    },
    shopId: {
        type: Schema.Types.ObjectId,
        ref: 'Shop',
        required: [true, "Shop ID is required"]
    },
    items: [orderItemSchema],
    subtotal: {
        type: Number,
        required: true,
        min: 0
    },
    shippingFee: {
        type: Number,
        default: 0,
        min: 0
    },
    discount: {
        type: Number,
        default: 0,
        min: 0
    },
    couponId: {
        type: Schema.Types.ObjectId,
        ref: 'Coupon',
        default: null
    },
    totalAmount: {
        type: Number,
        required: true,
        min: 0
    },
    status: {
        type: String,
        enum: [
            'PENDING',           // Chờ xử lý
            'CONFIRMED',         // Đã xác nhận
            'PREPARING',         // Đang chuẩn bị
            'READY',             // Sẵn sàng giao
            'SHIPPING',          // Đang giao hàng
            'DELIVERED',         // Đã giao
            'CANCELLED',         // Đã hủy
            'REFUNDED'           // Đã hoàn tiền
        ],
        default: 'PENDING'
    },
    paymentStatus: {
        type: String,
        enum: ['PENDING', 'PAID', 'FAILED', 'REFUNDED'],
        default: 'PENDING'
    },
    paymentMethodId: {
        type: Schema.Types.ObjectId,
        ref: 'paymentMethods',
        required: true
    },
    paymentCode: {
        type: String,
        trim: true
        // Store payment code (VNPAY, COD) for easy checking without populate
    },
    transactionId: {
        type: String,
        trim: true
    },
    paymentMeta: {
        type: Schema.Types.Mixed,
        default: {}
    },
    shippingMethodId: {
        type: Schema.Types.ObjectId,
        ref: 'ShippingMethod',
        required: true
    },
    shippingAddress: {
        address_line1: { type: String, required: true },
        address_line2: String,
        city: { type: String, required: true },
        district: String,
        ward: String,
        postalCode: String,
        phone: { type: String, required: true },
        recipientName: { type: String, required: true }
    },
    notes: {
        type: String,
        trim: true,
        maxlength: 500
    },
    deliveryDate: {
        type: Date
        // Ngày giao hàng dự kiến
    },
    deliveredAt: {
        type: Date
    },
    cancelledAt: {
        type: Date
    },
    cancellationReason: {
        type: String,
        trim: true
    },
    trackingNumber: {
        type: String,
        trim: true
    }
}, {
    timestamps: true
})

// Pre-save hook to auto-generate orderNumber if not provided
orderSchema.pre('save', async function(next) {
  // Only generate if orderNumber is not set
  if (!this.orderNumber) {
    const date = new Date()
    const dateStr = date.toISOString().slice(0, 10).replace(/-/g, '') // YYYYMMDD
    
    // Find the last order number for today to get the sequence
    const lastOrder = await this.constructor.findOne({
      orderNumber: { $regex: `^ORD-${dateStr}-` }
    }).sort({ orderNumber: -1 }).lean()
    
    let sequence = 1
    if (lastOrder && lastOrder.orderNumber) {
      const lastSeq = parseInt(lastOrder.orderNumber.split('-')[2] || '0', 10)
      sequence = lastSeq + 1
    }
    
    // Format: ORD-YYYYMMDD-XXXX (4 digits with leading zeros)
    this.orderNumber = `ORD-${dateStr}-${String(sequence).padStart(4, '0')}`
  }
  next()
})

// Indexes
orderSchema.index({ userId: 1, createdAt: -1 })
orderSchema.index({ shopId: 1, status: 1 })
orderSchema.index({ orderNumber: 1 }, { unique: true, sparse: true })
orderSchema.index({ status: 1, createdAt: -1 })


const Order = mongoose.model("Order", orderSchema)
module.exports = Order
